## NumPy 패키지 import

In [17]:
import numpy as np

## 배열 (array)

In [4]:
arr = np.array([0,1,2,3,4])
print(arr)

[0 1 2 3 4]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


### 벡터화 연산

In [7]:
num = [0,1,2,3,4]
result = [2 + i for i in num]
result

[2, 3, 4, 5, 6]

In [9]:
arr*2

array([0, 2, 4, 6, 8])

In [15]:
a = np.array([0,1,2])
b = np.array([2,4,6])
# 배열의 길이가 다르면 오류!

In [12]:
2*a + 3*b

array([ 6, 14, 22])

In [13]:
a == 2

array([False, False,  True])

In [14]:
(a == 1) & (b > 3)

array([False,  True, False])

### n차원 배열

In [19]:
na = np.array([[0,1,2],[3,4,5]])
na

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
print(len(na))    # 행의 개수
print(len(na[0])) # 열의 개수

2
3


In [21]:
# 3차원 (2 * 3 * 4 배열)
nb = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
               [[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
print(nb)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [23]:
print(nb.ndim)  # 배열의 차원
print(nb.shape) # 배열의 크기

3
(2, 3, 4)


## Quiz

In [31]:
arr1 = np.array([[10,20,30,40],[50,60,70,80]])
print(arr1.ndim)
print(arr1.shape)

2
(2, 4)


### 인덱싱

In [33]:
a = np.array([[0,1,2],[3,4,5]])
print(a[0,1])
print(a[-1,-1])

1
5


### 슬라이싱

In [36]:
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(b[0,1:3])
print(b[1:3,2])

[1 2]
[ 6 10]


## Quiz

In [37]:
m = np.array([[0,1,2,3,4],
             [5,6,7,8,9],
             [10,11,12,13,14]])

#### 1. 행렬에서 값 7을 인덱싱한다.

In [39]:
m[1,2]

7

#### 2. 행렬에서 값 14을 인덱싱한다.

In [42]:
# m[2,4]
m[-1,-1]

14

#### 3. 행렬에서 배열 [6, 7]을 슬라이싱한다.

In [51]:
m[1,1:3]

array([6, 7])

#### 4. 행렬에서 배열 [7, 12]을 슬라이싱한다.

In [49]:
m[1:,2]

array([ 7, 12])

#### 5. 행렬에서 배열 [[3, 4],[8,9]]을 슬라이싱한다.

In [53]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

## 배열 인덱싱 - 불(Boolean) 배열과 정수 배열 방식 존재

#### 불 배열 인덱싱

In [ ]:
a = np.array([0,1,2,3,4,5])  # 원래 배열
idx = np.array([True,False,True,False,True,False]) # 인덱스 배열
print(a[idx])

In [57]:
idx2 = a%2 == 0
idx2

array([ True, False,  True, False,  True, False])

In [58]:
a[a%2 == 0]

array([0, 2, 4])

#### 정수 배열 인덱싱

In [60]:
b = np.array([11,22,33,44,55,66])
idx3 = np.array([0,2,4])
print(b[idx]) # 원래 배열과 인덱스 배열의 크기가 달라도 관계없음

[11 33 55]


## Quiz

In [61]:
x = np.array([1,2,3,4,5,6,7,8,9,10,
              11,12,13,14,15,16,17,18,19,20])

#### 1. 배열에서 3의 배수를 찾아라. 

In [62]:
idx4 = x % 3 == 0
x[idx4]

array([ 3,  6,  9, 12, 15, 18])

#### 2. 배열에서 4로 나누면 1이 남는 수를 찾아라.

In [63]:
idx5 = x % 4 == 1
x[idx5]

array([ 1,  5,  9, 13, 17])

#### 3. 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [64]:
idx6 = (x % 3 == 0) & (x % 4 == 1)
x[idx6]

array([9])

## 브로드캐스팅 (broadcasting)

In [67]:
c = np.array([0,1,2,3,4])
c + 1

array([1, 2, 3, 4, 5])

In [79]:
x = np.arange(5)
y = np.ones_like(x)  # x와 같은 모양의 배열을 만듬 (요소가 1)
z = np.zeros_like(x) # x와 같은 모양의 배열을 만듬 (요소가 0)
print(x)
print(y) 
print(z)

[0 1 2 3 4]
[1 1 1 1 1]
[0 0 0 0 0]


In [81]:
x = np.array([[0,1,2],[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
y = np.array([0,1,2,3,4])
yt = y.reshape(5,1)   # y 배열의 모양을 변경
print(yt)
print(x + yt)

[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]


## 차원 축소 연산

In [87]:
x = np.array([1,4,2,3])

print(np.sum(x))     # 합
print(np.min(x))     # 최소값
print(np.max(x))     # 최대값
print(np.argmin(x))  # 최소값의 위치
print(np.argmax(x))  # 최대값의 위치
print(np.mean(x))    # 평균
print(np.median(x))  # 중간값

10
1
4
0
1
2.5
2.5


In [90]:
z = np.array([True,True,False])
print(np.all(z))  # 모든 데이터가 True면 True
print(np.any(z))  # 데이터가 하나라도 True면 True

False
True
